version: '2.1'
services:
  bluetooth-audio:
    build: ./bluetooth-audio
    restart: on-failure
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: 1
    volumes:
      - bluetoothcache:/var/cache/bluetooth
  pihole:
    build: ./pihole
    restart: on-failure
    network_mode: host
    privileged: true
    volumes:
      - pihole_config:/etc/pihole
      - dnsmasq_config:/etc/dnsmasq.d
    dns:
      - '1.0.0.1'
      - '1.1.1.1'
  notifier:
    build: ./notifier
    restart: on-failure
    network_mode: host
    privileged: true
    volumes:
      - notifier_config:/etc/notifier
volumes:
  bluetoothcache:
  pihole_config:
  dnsmasq_config:
  notifier_config:
