version: '2.1'
services:
  pihole:
    build: ./pihole
    restart: on-failure
    network_mode: host
    privileged: true
    volumes:
      - pihole_config:/etc/pihole
      - dnsmasq_config:/etc/dnsmasq.d
    dns:
      - "127.0.0.1"
      - "1.0.0.1"
    environment:
      DNSMASQ_LISTENING: eth0
      INTERFACE: eth0
      DNS1: 127.0.0.1#5053
      DNS2: 127.0.0.1#5053
    depends_on:
      - unbound  
      
  unbound:
    build: ./unbound
    privileged: true
    ports:
      - "5053:5053/tcp"
      - "5053:5053/udp"
  # https://github.com/balenablocks/fbcp
  #fbcp:
    #image: balenablocks/fbcp
    #privileged: true
    # restart: on-failure
    # labels:
    #     io.balena.features.dbus: "1"
    
  notifier:
    build: ./notifier
    restart: on-failure
    network_mode: host
    privileged: true
    volumes:
      - notifier_config:/etc/notifier
      
  
  nodejs-idex-staker:
    build: ./nodejs-idex-staker
    restart: on-failure
    network_mode: host
    privileged: true
    volumes:
      - idex_config:/etc/idexio
    ports:
      - "8081:8081/tcp"
volumes:
  pihole_config:
  dnsmasq_config:
  notifier_config:
  idex_config:
