FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3-latest-run

#switch on systemd init system in container
ENV INITSYSTEM on

RUN install_packages \
  build-essential \
  curl \
  apt-utils

# pip install python deps from requirements.txt
# For caching until requirements.txt changes
COPY ./requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

COPY . /usr/src/app
WORKDIR /usr/src/app

CMD ["python", "gpio_example.py"]
